version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    volumes:
      - /data # Анонимный том (Requirement Task 2)
    networks:
      - app_network

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    restart: on-failure # (Requirement Task 2 failure simulation)
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  # --- Админки (Requirement Task 1 Creative) ---
  adminer:
    image: adminer
    ports: ["8080:8080"]
    profiles: ["debug"]
    networks: ["app_network"]

  # --- Мониторинг (Requirement Task 5 Creative) ---
  prometheus:
    image: prom/prometheus
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
    networks: ["app_network"]

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    networks: ["app_network"]

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
